# fly.toml app configuration file generated for isee-api-staging-twilight-grass-3635 on 2025-04-06T12:31:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'isee-api-staging-twilight-grass-3635'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  FLASK_ENV = 'staging'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
